### ISSUE TITLE
Testing for new victor control stack

### ISSUE THREAD

**Issue by Yating05** [UM-ARM-Lab/victor_ros2#1]
Things to test 

- [ ] The coordinate frames of the end-effector wrenches should make sense and be documented
- [ ] Do a before/after test for  joint position speed, joint impedance, cartesian impedance, and end-effector wrench

**Comment by umicharmlab** [comment]
Debuggin/testing

I'm noticing that the FRI connections fail intermittently

**Comment by PeterMitrano** [comment]
I wrote a simple test script `TestFRI.cpp` to make it easier to debug FRI connection.

- [x] In "Monitoring" mode, the right arm runs for a really long time (>1hr) when the FRI loop is running at max speed.
- [x] Test the same thing but in position mode
- [x] Test the left arm
- [ ] Test both arms together
- [ ] Start adding some delays or sleeps in the main loop to see if we can get it to start failing

**Comment by zxhuang97** [comment]
Moving away from FRI approach
